services:
  app_prod:
    build:
      context: .
      target: prod # Make sure the Dockerfile has a production target
    image: auth-image-prod
    container_name: auth-container-prod
    command: ['npm', 'run', 'prod'] # Run the production script
    ports:
      - '3000:3000' # Expose the app port
    env_file:
      - .env.prod # Include environment variables for production
    volumes:
      - .:/usr/src/app # Mount the project directory to the container for live changes
      - /usr/src/app/node_modules
