services:
  app_dev:
    build:
      context: .
      target: dev # Make sure the Dockerfile has a development target
    image: auth-image-dev
    container_name: auth-container-dev
    command: ['npm', 'run', 'dev'] # Run the dev script
    ports:
      - '3000:3000' # Expose the app port
    env_file:
      - .env.dev # Include environment variables from .env file
    volumes:
      - .:/usr/src/app # Mount the project directory to the container for live changes
      - /usr/src/app/node_modules
